kind: PersistentVolume
apiVersion: v1
metadata:
  name: db-warehouse
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: db-warehouse
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi