apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: keycloak
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:19.0.3
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          args: ["start-dev"]
          envFrom:
            - configMapRef:
                name: keycloak
#          readinessProbe:
#            httpGet:
#              path: /realms/master
#              port: 8080
status: {}
