apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak
  labels:
    app: keycloak
data:
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: admin
  PROXY_ADDRESS_FORWARDING: "true"
  KC_DB: postgres
  KC_DB_USERNAME: postgres
  KC_DB_PASSWORD: dev
  KC_DB_URL_HOST: postgres
  KC_DB_URL_PORT: "5432"
  KC_DB_URL_DATABASE: keycloak
  KC_DB_SCHEMA: public
