apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres
  labels:
    app: postgres
data:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: dev
  POSTGRES_DB: warehouse
  init.sql: | 
    CREATE DATABASE keycloak;
