apiVersion: v1
kind: ConfigMap
metadata:
  name: warehouse
data:
  DB_HOST: db-warehouse
  DB_PORT: "7433"
  EPAGES_API_KEY: ylnUnbzYJLLBmhU6APZICaxqR4XGizcU
  KEYCLOAK_HOST: keycloak
  KEYCLOAK_PORT: "7001"
  KEYCLOAK_REALM: integration
