apiVersion: v1
kind: Service
metadata:
  name: warehouse
spec:
  type: NodePort
  selector:
    app: warehouse
  ports:
      - protocol: "TCP"
        port: 7001
        targetPort: 7001
        nodePort: 30001